site_name: EdgeX Foundry Documentation
docs_dir: ./docs_src
site_dir: ./docs/2.0
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Michael Johanson'
site_url: 'https://edgexfoundry.github.io/edgex-docs/'
repo_url: 'https://github.com/edgexfoundry/edgex-go'
repo_name: 'edgex/edgex-go'
copyright: 'Copyright &copy; 2020 EdgeX Foundry'
strict: true
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  analytics:
    gtag: 'G-38531ZZHBN'
  features:
    - tabs
nav:
  - Introduction:
    - 'index.md'
  - Getting Started:
      - './getting-started/index.md'
      - Quick Start: './getting-started/quick-start/index.md'
      - Users:
        - './getting-started/Ch-GettingStartedUsers.md'
        - './getting-started/Ch-GettingStartedSnapUsers.md'
      - Developers:
        - './getting-started/Ch-GettingStartedDevelopers.md'
        - './getting-started/Ch-GettingStartedGoDevelopers.md'
        - './getting-started/Ch-GettingStartedCDevelopers.md'
        - './getting-started/Ch-GettingStartedHybrid.md'
        - Application Functions SDK: './getting-started/ApplicationFunctionsSDK.md'
        - Device Services:
          - './getting-started/Ch-GettingStartedSDK.md'
          - './getting-started/Ch-GettingStartedSDK-C.md'
          - './getting-started/Ch-GettingStartedSDK-Go.md'
        - './getting-started/Ch-GettingStartedUsersNexus.md'
      - Tools:
        - './getting-started/tools/Ch-CommandLineInterface.md'
  - Security:
    - './security/Ch-Security.md'
    - './security/Ch-SecretStore.md'
    - './security/Ch-APIGateway.md'
    - './security/Ch-Secure-MessageBus.md'
    - './security/Ch-Configuring-Add-On-Services.md'
    - './security/Ch-Secure-Consul.md'
    - './security/Ch-SecurityIssues.md'
    - './security/secrets-config.md'
    - './security/secrets-config-proxy.md'
  - Microservices:
      - './microservices/general/index.md'
      - './microservices/V2TopLevelMigration.md'
      - Configuration & Registry:
        - './microservices/configuration/CommonConfiguration.md'
        - './microservices/configuration/CommonCommandLineOptions.md'
        - './microservices/configuration/CommonEnvironmentVariables.md'
        - './microservices/configuration/ConfigurationAndRegistry.md'
        - './microservices/configuration/V2MigrationCommonConfig.md'
      - Core Services:
        - './microservices/core/Ch-CoreServices.md'
        - './microservices/core/data/Ch-CoreData.md'
        - './microservices/core/metadata/Ch-Metadata.md'
        - './microservices/core/command/Ch-Command.md'
        - './microservices/core/database/Ch-Redis.md'
      - Supporting Services:
        - './microservices/support/Ch-SupportingServices.md'
        - './microservices/support/notifications/Ch-AlertsNotifications.md'
        - './microservices/support/eKuiper/Ch-eKuiper.md'
        - './microservices/support/scheduler/Ch-Scheduler.md'
      - System Management:
        - './microservices/system-management/Ch_SystemManagement.md'
        - './microservices/system-management/agent/Ch_SysMgmtAgent.md'
        - './microservices/system-management/executor/Ch_SysMgmtExecutor.md'
      - Devices Services:
        - './microservices/device/Ch-DeviceServices.md'
        - './microservices/device/profile/Ch-DeviceProfile.md'
        - './microservices/device/sdk/Ch-DeviceSDK.md'
        - './microservices/device/virtual/Ch-VirtualDevice.md'
        - './microservices/device/V2Migration.md'
      - Application Services:
        - Introduction: './microservices/application/ApplicationServices.md'
        - Getting Started: './microservices/application/GettingStarted.md'
        - Triggers: './microservices/application/Triggers.md'
        - Application Functions SDK:
            - './microservices/application/ApplicationFunctionsSDK.md'
            - './microservices/application/ApplicationServiceAPI.md'
            - './microservices/application/AppFunctionContextAPI.md'
            - './microservices/application/ErrorHandling.md'
            - './microservices/application/BuiltIn.md'
            - './microservices/application/AdvancedTopics.md'
        - './microservices/application/AppServiceConfigurable.md'
        - './microservices/application/GeneralAppServiceConfig.md'
        - './microservices/application/V2Migration.md'
  - Examples and Tutorials:
    - './examples/Ch-ExamplesVirtualDeviceService.md'
    - './examples/Ch-ExamplesSendingAndConsumingBinary.md'
    - './examples/AppServiceExamples.md'
    - './examples/Ch-CommandingDeviceThroughRulesEngine.md'
    - './examples/Ch-ExamplesModbusdatatypeconversion.md'
    - './examples/Ch-ExamplesRP4.md'
    - Adding a Device:
      - './examples/Ch-ExamplesAddingModbusDevice.md'
      - './examples/Ch-ExamplesAddingSNMPDevice.md'
      - './examples/Ch-ExamplesAddingMQTTDevice.md'
    - Walkthrough:
      - 'walk-through/Ch-Walkthrough.md'
      - 'walk-through/Ch-WalkthroughSetup.md'
      - 'walk-through/Ch-WalkthroughUseCase.md'
      - 'walk-through/Ch-WalkthroughData.md'
      - 'walk-through/Ch-WalkthroughDeviceProfile.md'
      - 'walk-through/Ch-WalkthroughDeviceService.md'
      - 'walk-through/Ch-WalkthroughProvision.md'
      - 'walk-through/Ch-WalkthroughCommands.md'
      - 'walk-through/Ch-WalkthroughReading.md'
      - 'walk-through/Ch-WalkthroughExporting.md'
    - './examples/LinuxTutorial/LinuxTutorial.md'
  - API Reference:
    - Introduction: './api/Ch-APIIntroduction.md'
    - Core:
      - './api/core/Ch-APICoreCommand.md'
      - './api/core/Ch-APICoreData.md'
      - './api/core/Ch-APICoreMetadata.md'
      - './api/core/Ch-APICoreConfigurationAndRegistry.md'
    - Support:
      - './api/support/Ch-APISupportNotifications.md'
      - './api/support/Ch-APISupportScheduler.md'
    - Management:
      - './api/management/Ch-APISystemManagement.md'
    - Device:
        - './api/devices/Ch-APIDeviceSDK.md'
    - Application:
        - './api/applications/Ch-APIAppFunctionsSDK.md'
        - './api/applications/Ch-APIRulesEngine.md'
  - Architectural Decision Records:
    - './design/README.md'
    - './design/TOC.md'
    - Legacy:
      - './design/legacy-design/README.md'
      - './design/legacy-requirements/README.md'
  - Reference:
    - './general/Definitions.md'
    - './general/PlatformRequirements.md'
    - './general/ServicePorts.md'
    - './general/ContainerNames.md'
    - './general/ServiceConfiguration.md'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - mdx_truly_sane_lists
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
extra_css:
- assets\stylesheets\version-select.css
- assets\stylesheets\branding.css
- assets\stylesheets\edgey.css
- assets\stylesheets\newexample.css
extra_javascript:
- assets\javascripts\version-select.js
