site_name: EdgeX Foundry Documentation
docs_dir: ./docs_src
site_dir: ./docs/3.0
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Michael Johanson'
site_url: 'https://docs.edgexfoundry.org/3.0'
repo_url: 'https://github.com/edgexfoundry/edgex-go'
repo_name: 'edgex/edgex-go'
copyright: 'Copyright &copy; 2022 EdgeX Foundry'
strict: false   # mkdocs-materials will prevent running on 0.0.0.0 otherwise (or have custom image)
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  features:
    - navigation.tabs  # changed with version 6 of mkdocs-materials
nav:
  - Introduction:
    - 'index.md'
    - 'V2TopLevelMigration.md'
  - Getting Started:
      - './getting-started/index.md'
      - Quick Start: './getting-started/quick-start/index.md'
      - Users:
        - './getting-started/Ch-GettingStartedUsers.md'
        - './getting-started/Ch-GettingStartedDockerUsers.md'
        - './getting-started/Ch-GettingStartedSnapUsers.md'
      - Developers:
        - './getting-started/Ch-GettingStartedDevelopers.md'
        - './getting-started/Ch-GettingStartedGoDevelopers.md'
        - './getting-started/Ch-GettingStartedCDevelopers.md'
        - './getting-started/Ch-GettingStartedHybrid.md'
        - Native Build and Run Guides:
          - './getting-started/native/Ch-BuildRunNative.md'
          - './getting-started/native/Ch-BuildRunOnLinuxDistro.md'
          - './getting-started/native/Ch-BuildRunOnArm32.md'
          - './getting-started/native/Ch-BuildRunOnWindows.md'
        - Application Functions SDK: './getting-started/ApplicationFunctionsSDK.md'
        - Device Services:
          - './getting-started/Ch-GettingStartedSDK.md'
          - './getting-started/Ch-GettingStartedSDK-C.md'
          - './getting-started/Ch-GettingStartedSDK-Go.md'
        - './getting-started/Ch-GettingStartedUsersNexus.md'
        - './getting-started/Ch-GettingStartedDTOValidation.md'
      - Tools:
        - './getting-started/tools/Ch-CommandLineInterface.md'
        - './getting-started/tools/Ch-GUI.md'
  - Security:
    - './security/Ch-Security.md'
    - './security/Ch-SecretStore.md'
    - './security/Ch-Authenticating.md'
    - './security/Ch-SecretProviderApi.md'
    - './security/Ch-APIGateway.md'
    - './security/Ch-Secure-MessageBus.md'
    - './security/Ch-Configuring-Add-On-Services.md'
    - './security/Ch-Secure-Consul.md'
    - './security/Ch-SecurityIssues.md'
    - './security/secrets-config.md'
    - './security/secrets-config-proxy.md'
    - './security/SeedingServiceSecrets.md'
    - './security/Ch-CORS-Settings.md'
    - './security/Ch-DelayedStartServices.md'
    - './security/Ch-RemoteDeviceServices.md'
    - Threat Models:
      - './threat-models/secret-store/README.md'
      - './threat-models/stride-model/EdgeX-STRIDE.md'
      - './threat-models/stride-model/EdgeXFoundryThreatReportV2.2.md'
  - Microservices:
      - './microservices/general/index.md'
      - Configuration & Registry:
        - './microservices/configuration/CommonConfiguration.md'
        - './microservices/configuration/CommonCommandLineOptions.md'
        - './microservices/configuration/CommonEnvironmentVariables.md'
        - './microservices/configuration/ConfigurationAndRegistry.md'
        - './microservices/configuration/V3MigrationCommonConfig.md'
      - './microservices/general/messagebus.md'
      - Core Services:
        - './microservices/core/Ch-CoreServices.md'
        - './microservices/core/data/Ch-CoreData.md'
        - './microservices/core/metadata/Ch-Metadata.md'
        - './microservices/core/command/Ch-Command.md'
        - './microservices/core/database/Ch-Redis.md'
      - Supporting Services:
        - './microservices/support/Ch-SupportingServices.md'
        - './microservices/support/notifications/Ch-AlertsNotifications.md'
        - './microservices/support/scheduler/Ch-Scheduler.md'
        - './microservices/support/eKuiper/Ch-eKuiper.md'
      - Devices Services:
        - ONVIF:
          - Walkthrough:
            - './microservices/device/ONVIF/walkthrough/setup.md'
            - './microservices/device/ONVIF/walkthrough/custom-build.md'
            - './microservices/device/ONVIF/walkthrough/running-guide.md'
            - './microservices/device/ONVIF/walkthrough/general-usage.md'
          - './microservices/device/ONVIF/General.md'
          - './microservices/device/ONVIF/1.md'
          - './microservices/device/ONVIF/2.md'
        - './microservices/device/Ch-DeviceServices.md'
        - './microservices/device/Ch-DeviceServiceList.md'
        - './microservices/device/profile/Ch-DeviceProfile.md'
        - './microservices/device/sdk/Ch-DeviceSDK.md'
        - Device SDK API:
          -  './microservices/device/sdk/SDK-Go-API.md'
        - './microservices/device/virtual/Ch-VirtualDevice.md'
        - './microservices/device/V2Migration.md'
      - Application Services:
        - Introduction: './microservices/application/ApplicationServices.md'
        - Getting Started: './microservices/application/GettingStarted.md'
        - Triggers: './microservices/application/Triggers.md'
        - Application Functions SDK:
            - './microservices/application/ApplicationFunctionsSDK.md'
            - './microservices/application/ApplicationServiceAPI.md'
            - './microservices/application/AppFunctionContextAPI.md'
            - './microservices/application/ErrorHandling.md'
            - './microservices/application/BuiltIn.md'
            - './microservices/application/AdvancedTopics.md'
        - './microservices/application/AppServiceConfigurable.md'
        - './microservices/application/GeneralAppServiceConfig.md'
        - './microservices/application/V2Migration.md'
  - Examples and Tutorials:
    - './examples/index.md'
    - './examples/Ch-ExamplesVirtualDeviceService.md'
    - './examples/Ch-ExamplesUsbDeviceService.md'
    - './examples/Ch-ExamplesSendingAndConsumingBinary.md'
    - './examples/AppServiceExamples.md'
    - './examples/Ch-CommandingDeviceThroughRulesEngine.md'
    - './examples/Ch-ExamplesModbusdatatypeconversion.md'
    - './examples/Ch-OSImageWithEdgeX.md'
    - Adding a Device:
      - './examples/Ch-ExamplesAddingModbusDevice.md'
      - './examples/Ch-ExamplesAddingSNMPDevice.md'
      - './examples/Ch-ExamplesAddingMQTTDevice.md'
    - Walkthrough:
      - 'walk-through/Ch-Walkthrough.md'
      - 'walk-through/Ch-WalkthroughSetup.md'
      - 'walk-through/Ch-WalkthroughUseCase.md'
      - 'walk-through/Ch-WalkthroughDeviceProfile.md'
      - 'walk-through/Ch-WalkthroughDeviceService.md'
      - 'walk-through/Ch-WalkthroughProvision.md'
      - 'walk-through/Ch-WalkthroughCommands.md'
      - 'walk-through/Ch-WalkthroughReading.md'
      - 'walk-through/Ch-WalkthroughExporting.md'
  - API Reference:
    - Introduction: './api/Ch-APIIntroduction.md'
    -  './api/core/Ch-APICoreCommand.md'
    - './api/core/Ch-APICoreData.md'
    - './api/core/Ch-APICoreMetadata.md'
    - './api/core/Ch-APICoreConfigurationAndRegistry.md'
    - './api/support/Ch-APISupportNotifications.md'
    - './api/support/Ch-APISupportScheduler.md'
    - './api/devices/Ch-APIDeviceSDK.md'
    - './api/applications/Ch-APIAppFunctionsSDK.md'
    - './api/applications/Ch-APIRulesEngine.md'
  - Use Cases & Designs:
    - './design/Process.md'
    - './design/TOC.md'
    - Legacy:
      - './design/legacy-design/README.md'
      - './design/legacy-requirements/README.md'
  - Reference:
    - './general/Definitions.md'
    - './general/PlatformRequirements.md'
    - './general/ServicePorts.md'
    - './general/ContainerNames.md'
    - './general/ServiceConfiguration.md'
    - './general/EdgeX_CN.md'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - tables
  # - mdx_truly_sane_lists
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
  analytics:
    provider: google
    property: G-38531ZZHBN
extra_css:
- assets/stylesheets/version-select.css
- assets/stylesheets/branding.css
- assets/stylesheets/edgey.css
- assets/stylesheets/newexample.css
extra_javascript:
- assets/javascripts/version-select.js
plugins:
  - search
  - swagger-ui-tag
  - macros:
      include_yaml:
        - template_macros.yaml
      on_error_fail: true
  - htmlproofer:
      enabled: !ENV [ENABLED_HTMLPROOFER, false]
      raise_error: true
      raise_error_excludes:
        404: ['https://support.google.com/accounts/answer/185833?hl=en',
              'https://support.google.com/accounts/answer/6010255?hl=en']
        429: ['*']
        -1: ['https://www.rfc-editor.org/rfc/rfc7519',
             'https://tools.ietf.org/html/rfc5869','https://docs.iotaap.io/docs-rest/']
        500: [https://packages.ubuntu.com/bionic/build-essential]
