site_name: EdgeX Foundry Documentation
docs_dir: ./docs_src
site_dir: ./docs/1.2
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Michael Johanson'
site_url: 'https://edgexfoundry.github.io/edgex-docs/'
repo_url: 'https://github.com/edgexfoundry/edgex-go'
repo_name: 'edgex/edgex-go'
copyright: 'Copyright &copy; 2020 EdgeX Foundry'
google_analytics:
  - 'UA-82811140-6'
  - 'auto'
strict: true
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  features:
    - tabs
nav:
  - 'index.md'
  - Getting Started:
      - './getting-started/index.md'
      - Quick Start: './getting-started/quick-start/index.md'
      - Users:
        - './getting-started/Ch-GettingStartedUsers.md'
      - Developers:
        - './getting-started/Ch-GettingStartedDevelopers.md'
        - './getting-started/Ch-GettingStartedGoDevelopers.md'
        - './getting-started/Ch-GettingStartedHybrid.md'
        - Application Functions SDK: './getting-started/ApplicationFunctionsSDK.md'
        - Device Services:
          - './getting-started/Ch-GettingStartedSDK.md'
          - './getting-started/Ch-GettingStartedSDK-C.md'
          - './getting-started/Ch-GettingStartedSDK-Go.md'
        - './getting-started/Ch-GettingStartedUsersNexus.md'
  - Microservices:
      - Core Services:
        - './microservices/core/data/Ch-CoreData.md'
        - './microservices/core/metadata/Ch-Metadata.md'
        - './microservices/core/command/Ch-Command.md'
      - Supporting Services:
        - './microservices/support/Ch-SupportingServices.md'
        - './microservices/support/logging/Ch-Logging.md'
        - './microservices/support/notifications/Ch-AlertsNotifications.md'
        - './microservices/support/rulesengine/Ch-RulesEngine.md'
        - './microservices/support/Kuiper/Ch-Kuiper.md'
        - './microservices/support/scheduler/Ch-Scheduling.md'
      - System Management:
        - './microservices/system-management/agent/Ch_SysMgmtAgent.md'
      - Security:
        - './microservices/security/Ch-Security.md'
        - './microservices/security/Ch-SecretStore.md'
        - './microservices/security/Ch-APIGateway.md'
        - './microservices/security/Ch-AccessEdgeXRESTResources.md'
        - './microservices/security/Ch-StartingSecurity.md'
        - './microservices/security/Ch-SecurityIssues.md'
      - Devices Services:
        - './microservices/device/Ch-DeviceServices.md'
        - './microservices/device/profile/Ch-DeviceProfile.md'
        - './microservices/device/sdk/Ch-DeviceSDK.md'
        - './microservices/device/virtual/Ch-VirtualDevice.md'
      - Application Services:
        - Introduction: './microservices/application/ApplicationServices.md'
        - Triggers: './microservices/application/Triggers.md'
        - './microservices/application/ApplicationFunctionsSDK.md'
        - './microservices/application/AppServiceConfigurable.md'
        - './microservices/application/GeneralAppServiceConfig.md'
      - './microservices/configuration/Ch-Configuration.md'
  - Examples and Tutorials:
    - './examples/Ch-ExamplesProvisionDevice.md'
    - './examples/Ch-ExamplesModbusdatatypeconversion.md'
    - './examples/Ch-ExamplesVirtualDeviceService.md'
    - './examples/Ch-ExamplesRandomDeviceService.md'
    - './examples/Ch-ExamplesSendingAndConsumingBinary.md'
    - './examples/AppServiceExamples.md'
    - Adding a Device:
      - './examples/Ch-ExamplesAddingModbusDevice.md'
      - './examples/Ch-ExamplesAddingSNMPDevice.md'
      - './examples/Ch-ExamplesAddingMQTTDevice.md'
    - Walkthrough:
      - 'walk-through/Ch-Walkthrough.md'
      - 'walk-through/Ch-WalkthroughSetup.md'
      - 'walk-through/Ch-WalkthroughRunning.md'
      - 'walk-through/Ch-WalkthroughUseCase.md'
      - 'walk-through/Ch-WalkthroughData.md'
      - 'walk-through/Ch-WalkthroughDeviceProfile.md'
      - 'walk-through/Ch-WalkthroughDeviceService.md'
      - 'walk-through/Ch-WalkthroughProvision.md'
      - 'walk-through/Ch-WalkthroughCommands.md'
      - 'walk-through/Ch-WalkthroughReading.md'
      - 'walk-through/Ch-WalkthroughExporting.md'
  - API Reference: 
    - Core:
      - './api/core/Ch-APICoreCommand.md'
      - './api/core/Ch-APICoreData.md'
      - './api/core/Ch-APICoreMetadata.md'
      - './api/core/Ch-APICoreServiceConfiguration.md'
    - Supporting Services:
      - './api/supporting/Ch-APISupportingServicesAlerts.md'
      - './api/supporting/Ch-APISupportingServicesLogging.md'
      - './api/supporting/Ch-APISupportingServicesRulesEngine.md'
      - './api/supporting/Ch-APISupportingServicesScheduling.md'
    - './api/Ch-APIDeviceSDK.md'
    - './api/Ch-APISystemManagement.md'
    - './api/Ch-APIAppFunctionsSDK.md'
  - Architectural Decision Records:
    - './design/README.md'
    - './design/TOC.md'
    - Legacy:
      - './design/legacy-design/README.md'
      - './design/legacy-requirements/README.md'
  - Definitions:
      - './general/Definitions.md'
markdown_extensions:
  - codehilite
  - admonition
  # - mdx_truly_sane_lists
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
extra_css:
- assets\stylesheets\version-select.css
- assets\stylesheets\branding.css
extra_javascript:
- assets\javascripts\version-select.js
